webserver:
  port: 10150
  host: 0.0.0.0
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  host: 0.0.0.0
  port: 10158

readiness:
  db-connectivity-attempts: 120
  min-sample-interval: 2000

pgpool:
  connect-options:
    port: 15432
    host: localhost
    database: secret_service
    user: secret_service
    password: secret_service
  pool-options:
    max-size: 5

flyway:
  url: jdbc:postgresql://localhost:15432/secret_service
  user: secret_service
  password: secret_service

auth-service:
  host: localhost
  port: 10108
